[BitTorrent]
Session\AnonymousModeEnabled=true
Session\DHTEnabled=true
Session\PeXEnabled=false
Session\LSDEnabled=false
Session\DefaultSavePath=/downloads
Session\Interface=tun0
Session\InterfaceName=tun0
Session\MaxConnections=200
Session\MaxConnectionsPerTorrent=50
Session\BTProtocol=TCP

[Network]
Proxy\Type=0

[Preferences]
WebUI\Port=8080
WebUI\LocalHostAuth=true
WebUI\AuthSubnetWhitelistEnabled=false
WebUI\HostHeaderValidation=false
WebUI\HTTPS\Enabled=false
Downloads\SavePath=/downloads
Downloads\TempPath=/downloads/incomplete
Downloads\TempPathEnabled=true
General\Locale=en
